/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#4c4546",
        "outline-variant": "#cfc4c5",
        "tertiary": "#000000",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-container": "#1b1b1b",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-container": "#838484",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-low": "#f3f3f4",
        "secondary": "#5e5e5e",
        "on-primary-container": "#848484",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary-container": "#646464",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#1a1c1c",
        "secondary-container": "#e3e2e2",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1b1b1b",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#454747",
        "inverse-surface": "#2f3131",
        "surface-container": "#eeeeee",
        "tertiary-fixed-dim": "#c6c6c7",
        "inverse-primary": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "background": "#f9f9f9",
        "surface-dim": "#dadada",
        "inverse-on-surface": "#f0f1f1",
        "on-surface": "#1a1c1c",
        "primary": "#000000",
        "primary-fixed": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "outline": "#7e7576",
        "surface": "#f9f9f9",
        "secondary-fixed": "#e3e2e2",
        "on-primary-fixed-variant": "#474747",
        "surface-container-highest": "#e2e2e2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "section-gap": "128px",
        "gutter": "32px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "label-caps": ["Inter"],
        "display-lg": ["Playfair Display"],
        "mono-label": ["Inter"],
        "headline-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "38px", "fontWeight": "600" }],
        "display-lg-mobile": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display-lg": ["84px", { "lineHeight": "92px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "mono-label": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "32px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
};
